### ISSUE TITLE
Don't add spaces into CC fields when you use @... for adding user

### ISSUE THREAD

**Issue by Cyclodex** [trac-hacks/trac-mentions#5]
If you add Users with @... the list will be "comma + space" (, ) delimited.
However if you comment again without changing the values, Trac mentiones that it will change the Users:

> Cc changed from Cyclodex, Spot to Cyclodex,Spot

I am not 100% sure if this goes into this mentions plugin or trac itselfe.
Somehow I also can reproduce this with trac itself, but perhaps this plugin should not put the space in it.

**Comment by rjollos** [comment]
Fixed in https://github.com/trac-hacks/trac-mentions/commit/73fa8587e7c1fd6351ae0eba6973a27d7c3b2612.
